title: Sistema de Inventario de Cajones - GAB
description: Documentaci√≥n oficial del sistema web para captura y dashboard de inventario de cajones armables (GAB)

baseurl: ""
url: "https://jgalvanmr.github.io"

theme: minima

lang: es-MX
timezone: America/Mexico_City

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
